### ISSUE TITLE
Download ALL button :)

### ISSUE THREAD

**Issue by ghost** [tomasruud/downcloud#2]
a button that downloads all my tracks in one take

**Comment by animanoir** [comment]
I le agree

**Comment by tomasruud** [comment]
This is not a bad idea. The only problem is that this is kinda tricky to solve in client-side JavaScript only. On one hand I could make it so all links are opened in new tabs and needs to be downloaded one-by-one. This is probably very tedious and the preferred solution would be to make JavaScript zip all the files, client-side. I don't know how this will work with a lot of large WAV-files, but it should be possible. I'll look into it.

**Comment by tomasruud** [comment]
This has kinda been implemented now, but it doesn't work in all browsers, and it seems like there aren't many solutions to this. I'm going to close it for now. The best way to do this is probably to use an extension or a 3rd party application to do the downloading, as multi-download in browsers are not really supported at the moment.
