### ISSUE TITLE
Not logging in after verifying 

### ISSUE THREAD

**Issue by Allowsh28** [tomasruud/downcloud#3]
keeps loading and never logs in after authorising Downcloud on my souncloud account.
It never change the signup window - any suggestions?  
Desktop - Chrome  Version 67.0.3396.87

**Comment by tomasruud** [comment]
That's weird. Could you try sending me a dump/screenshot of the javascript console. You can do that by just right clicking the page, choose "Inspect element" or something like that, and go to the "Console" tab in the developer tools that opens.

**Comment by Allowsh28** [comment]
<img width="1422" alt="screen shot 2018-06-27 at 11 34 10 am" src="https://user-images.githubusercontent.com/40619783/41959462-1abc16ec-79fe-11e8-8af5-f303468480c9.png">

**Comment by tomasruud** [comment]
Thank you! I posted a fix for this now. I'll let you know when it becomes active.

**Comment by tomasruud** [comment]
The change is live now. Please let me know if it works.

**Comment by Allowsh28** [comment]
This worked Thanks.
Can I get your email, I want to propose a feature update to your software.

**Comment by tomasruud** [comment]
Awesome! 

That would be great, I would prefer if you just created a new issue with your feature here on Github, so I have everything tracked. 😄

**Comment by Allowsh28** [comment]
Not a problem, I wanted to see if we can back up all metadata and stats of my souncloud account in an open format. 
If you can give me a contact email, we may negotiate a price if its doable?

**Comment by tomasruud** [comment]
I generally do this as a hobby project whenever I feel for it and have the time. It's not my job, so I don't need to get paid to do this (I might set up something that makes donating possible). Please post a new issue here https://github.com/tomasruud/downcloud/issues/new describing a bit more in detail what data you want exported, and we'll take it from there. 😉
