### ISSUE TITLE
Metadata and stats 

### ISSUE THREAD

**Issue by Allowsh28** [tomasruud/downcloud#4]
I wanted to see if we can back up all metadata and stats of my souncloud account in an open format.

**Comment by tomasruud** [comment]
I'm kinda limited to the data that the Soundcloud API provides, but I think it would be possible to dump significant amount of data from there. The API returns everything as JSON, so I think that would go as an "open format". Are you thinking both track metadata (like plays, comments, bpm, key etc.) and profile metadata (like follower count, profile image etc.) or only track meta?

**Comment by Allowsh28** [comment]
Amazing, sure - Any data collection would help. The more the better.

**Comment by tomasruud** [comment]
bd8e7c3bb09bab2c22186a42a7b017373f5e809b is a step towards more data at least. I have made both user data and track data available as json for people wanting more data.
