### ISSUE TITLE
Not An Issue, Don’t know how else to contact you.

### ISSUE THREAD

**Issue by freesoui** [tomasruud/downcloud#9]
Seems like a good tool! 
Is it possible to download other users og uncompressed files though?
It would be cool to rip artists tracks in the original way they were uploaded, of course there are tools that rip in 256 AAC .m4a that aren't upscaled but if ripping og files from other users was possible.... I just thought you would know!
I know there used to be a working method....
Thanks! Cool tool btw

**Comment by tomasruud** [comment]
@freesoui unfortunately that is not possible, this tool is using Soundclouds internal API to get the tracks, and the download links requires a token connected to the user in order to download a track. So a user is only able to get her own tracks through the API.
